spring:
  datasource:
    password : qwer1234
    url : jdbc:mysql://localhost:3306/links
    username : root
  jpa :
    hibernate :
      ddl-auto : create
    properties :
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show_sql: true